language: java
jdk:
- oraclejdk8
after_success:
- mvn clean test jacoco:report coveralls:report
notifications:
  webhooks:
    urls:
    - http://52.207.210.73/api/webhooks/travis-ci.php
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
deploy:
  provider: s3
  access_key_id: AKIAJKRH4SORRDP74JXQ
  secret_access_key:
    secure: "ZjDBVMmfBnZdJQvK1jDN6SVQSp5mYzD2tTXLNR1+Y44VEmnZxSqCLbqkAT1EEDTYHedF+msmA59z6ytUd6LmqNoAw3SfNmLtGyU2/tSAzWBUEI+NiDV8pKNTxZGFCSqxUSvyBpNjfNrgQ4Zw9IbU9EdItcy8QIMZijOMJOzCA9OgjCnrL4J53rDbYuxVepc2CpBUc29Kr3oR/0msdXjtCCl8fzfJTx6JB5FYXlRli7RqHNelyo51ZANUt8l0jtBrXP0e5DRU1YXuxuli1PgRdzVl+xYZVYOmzjEPiZVkbRVu+h5GHc1XRxXSQF3Pz6N1086DimryNd7CGAiUf6MNXdNw+c8eVNZ/fh5J4/n85BDJVq9wrDKY/WLtSKT90AsyLmQwSDWCxeoMquDcWUV60kPujwsJkQN8Sr0Zlf4639Z+h9lDCgDQ767lE1FILJb0Alaa3vPx9crAbbTMdE76B8977ciuPl3oOe1b9GQme79bksaaqrlChqU8WkoS1bIw+Id/7HHL6A/I6g9mDANlt3/2eh+efq2dacudOtFMIkQjHV19dD1E9ICpvqFXJKVyF2DUca1Q3vyQRBXQCfypF9lNvf0twfwA7JTVYeRxRDoi5cz4ru7bMt73CQT1zvUEKtET7kwgzlbFuyDg8uYPWQNHFFEL5ToX736wOvesG1k="
  bucket: discord-java
  acl: public_read
  on:
    branch: master
