language: java
jdk:
- oraclejdk8
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  webhooks:
    secure: "TuzjnaOxOqMsC/c0mMAuQucPRcE6/MeB54NH4zJD+CIHqoHVJNBSry1Ix5iIyvsFJ3/D3Rx7gmeJzPwGa+jN31wK69kPwdprhO8nsiWfExHugHu+hwBvul2QgSOpDONaspJfA2M/svJu6Ywt7n6ZQakqg6cWndfxwsBzBYESdMXQ6NZQ9Lfa+8pLioEmpz88AOkxyUEkzi49OzYzZCSqNWNWtiaPA311QAyu8gyk5Ot6fiAFA2CsJ8uoVU/pezROUZBxJfDp1HY42ZWGvdfWqhpGDqEHCPLD1Wihh9GiFYyA+fcc4eXJYNImlBm/d1wQj7/TImiVpN/ghT3dZb9VHs8FqaJil/MxX08eNQ5ivuv7xcPXBwCdb2bC5w7JwZVtAUlWeEzLDmS0UdejZhb2l54eRw741acakyBglDUMIj1+PDmwOs08ahQvytBsUmiXiwxvZMeRQVfHwxlrg1uCB96JBmleKulOtJwWo/hmqFQz6a+Etgt/bYygmXZGAU9KkM64XiCkrVY+Lx5vDZjxBri5LRyLhnEGZ55uHjsp4YkUjQKH2VUE0wsGOWu9DNvfur6ZokA5ab1VexmioL1Zv2mkIUFaQCinal+xhMETtMuES0HygzREY1B/hZ4jFVETcxBpnZtLsv1fRSbgBLufDS/1xGyn/hdVo+oa+VeZ8xo="
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
