language: java
jdk:
- oraclejdk8
notifications:
  email: false
  webhooks: http://vps.ajpappas.net/api/webhooks/travis-ci.php
  on_success: always
  on_failure: always
  on_start: always
  on_cancel: always
  on_error: always
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
