language: java
jdk:
  - oraclejdk8
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  discord:
    channels:
      - DISCORD_WEBHOOK_ID:DISCORD_WEBHOOK_SECRET
    pull_request_template:
      - 'Build [#%{build_number}](%{build_url}) ([%{commit}](%{compare_url})) of %{repository}@%{branch} in PR [#%{pull_request_number}](%{pull_request_url}) by %{author} %{result} in %{duration}'
    branch_template:
      - 'Build [#%{build_number}](%{build_url}) ([%{commit}](%{compare_url})) of %{repository}@%{branch} by %{author} %{result} in %{duration}'