language: java
jdk:
- oraclejdk8
after_success:
- mvn clean test jacoco:report coveralls:report
notifications:
  webhooks:
    urls:
    - http://52.207.210.73/api/webhooks/travis-ci.php
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
deploy:
  provider: s3
  access_key_id: AKIAJKRH4SORRDP74JXQ
  secret_access_key:
    secure: "puQVL57WtYB8KdkQVKdsiDQ7mP8yeVO1l81k02J63j6WttYCTzWmutKNzQdqvz+Cf7mo77gwf26cZo0+/wJA/1jzxQjXDtBOJNf0YlLj5h4rRbXT/r5+BB/mQftl4Vf2Nmma4nD9CtPUaND0jYO63xdQzTjTzQwpGMCYHhFaEGAvrYwQ1ySfBpBmpMGpUY+9fbIjOMQJG0HjBV99wP5QkthGoy76XG9oMoogJIfPiIfqda36v6zYyCV5RIWY3gqCvjmkCkpOgsgkuONNqtNUEl8EkL0V0qst+mcwv108dg6Jej/nwN1tZlDnzbCbReSPHbJBnn4d9VJZ0kg44Aqy7IqRA/5trX8Meo7q3Pc1vjLd/gBPJYNz7JTEz/daUVCK6+r2I9D+f9lrHRJ3XFw0mQSO+Rc26u1P1b07VhBVvLw79Lk8nIpKGNtQv/4u3pdz2gAFVM8I6Hh1wv4Bn2Ypl2ZvdSTx6SCPhsLejT8taMzq/tFGbVqwsRHHNTp5fX7F/5Zhgjh76CNGyohO95uUTP/VU2yrWFUJEybDZu7M+dZPtoguqJUb+z5+lv1wLoo+crjdkJ+rBJATfSafTIc+2yn35Ju4GCOtiW2LB1Mb5BfmkSl44MUmjyT1bfbFPGNlDPALOCqcl3iMn/Gf2JXoVOHNv9Ju60qWj/2KKtqNWxc="
  bucket: discord-java
  acl: public_read
  on:
    branch: master
