language: java
jdk:
- oraclejdk8
notifications:
  email: false
  webhooks: http://bolt.ajpappas.net/api/webhooks/travis-ci.php
  on_success: always
  on_failure: always
  on_start: always
  on_cancel: always
  on_error: always
  
