language: java
jdk:
- oraclejdk8
after_success:
- mvn clean test jacoco:report coveralls:report
notifications:
  webhooks:
    urls:
    - http://52.207.210.73/api/webhooks/travis-ci.php
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
deploy:
  provider: s3
  access_key_id: AKIAJKRH4SORRDP74JXQ
  secret_access_key:
    secure: YsyspTA+tiax7T2MOy1rE2xGtERIpj81zyWZUNKC16rbj9xtEKskiGiqDgsIV180lYC2wPTopHtV6GE69c5VNT1uV63swMIs/R1tIc7+tcbhKL5dvG4elaJohDx6XHW1FJAHZg6c6sqPfsiv0jhJB3PP03mqHUGnomjWRBeYnaZQ7gzCLPa/XaKXt4gG9WqXeSEKTxuSjC09iqbGC54Nct3C+nGLQUv9$
  bucket: discord-java
  acl: public_read
  on:
    branch: master
