name: Gradle Build

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Setup gradle permissions
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
